package com.revature.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.revature.dto.AddOrUpdateClientDTO;
import com.revature.models.Clients;
import com.revature.util.JDBCUtility;

public class ClientsDAO {

	public Clients insertClients(AddOrUpdateClientDTO clients) throws SQLException {

		try (Connection con = JDBCUtility.getConnection()) {

			String sql = "INSERT INTO \r\n"
					+ "	clients (client_first_name, client_last_name, "
					+ "street_address, city, state, zip_code, email, phone_number)\r\n"
					+ "VALUES\r\n"
					+ "(?, ?, ?, ?, ?, ?, ?, ?);";
			PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

			ps.setString(1, clients.getFirstName());
			ps.setString(2, clients.getLastName());
			ps.setString(3, clients.getStreetAddress());
			ps.setString(4, clients.getCity());
			ps.setString(5, clients.getState());
			ps.setString(6, clients.getZipCode());
			ps.setString(7, clients.getEmail());
			ps.setString(8, clients.getPhoneNumber());
			
			ps.execute();
			
			ResultSet rs = ps.getGeneratedKeys();
			
			rs.next();		
			int autoGeneratedKey = rs.getInt(1);
			
			return new Clients(autoGeneratedKey, clients.getFirstName(), clients.getLastName(), clients.getStreetAddress(), clients.getCity(), clients.getState(),
					clients.getZipCode(), clients.getEmail(), clients.getPhoneNumber());
		}

		
	}

	public List<Clients> selectAllClients() throws SQLException {

		List<Clients> listOfClients = new ArrayList<>();

		try (Connection con = JDBCUtility.getConnection()) {

			String sql = "SELECT * FROM clients";
			PreparedStatement ps = con.prepareStatement(sql);

			ResultSet rs = ps.executeQuery();

			while (rs.next()) {

				listOfClients.add(new Clients(rs.getInt("client_id"), rs.getString("client_first_name"),
						rs.getString("client_last_name"), rs.getString("street_address"),
						rs.getString("city"), rs.getString("state"), rs.getString("zip_code"), rs.getString("email"),
						rs.getString("phone_number")));

//				int id = rs.getInt("client_id");
//				String firstName = rs.getString("client_first_name");
//				String lastName = rs.getString("client_last_name");
//				
//				Clients clients = new Clients(id, firstName, lastName);
//				
//				listOfClients.add(clients);
			}
			
		}
		return listOfClients;

	}

	public Clients selectClientsById(int id) throws SQLException {

		try (Connection con = JDBCUtility.getConnection()) {

			String sql = "SELECT * FROM clients WHERE client_id = ?";
			PreparedStatement ps = con.prepareStatement(sql);

			ps.setInt(1, id);

			ResultSet rs = ps.executeQuery();

			if (rs.next()) {
				return new Clients(rs.getInt("client_id"), rs.getString("client_first_name"),
						rs.getString("client_last_name"), rs.getString("street_address"),
						rs.getString("city"), rs.getString("state"), rs.getString("zip_code"), rs.getString("email"),
						rs.getString("phone_number"));
			} else {
				return null;
			}
		}
	}

	public Clients updateClientsById(int id, AddOrUpdateClientDTO clients) throws SQLException {

	

		try (Connection con = JDBCUtility.getConnection()) {

			String sql = "UPDATE clients\r\n"
					+ "SET client_first_name = ?, client_last_name = ?, street_address = ?, city = ?, state = ?, \r\n"
					+ "zip_code = ?, email = ?, phone_number = ?\r\n"
					+ "WHERE\r\n"
					+ "client_id = ?;";
			PreparedStatement ps = con.prepareStatement(sql);
			
			ps.setString(1, clients.getFirstName());
			ps.setString(2, clients.getLastName());
			ps.setString(3, clients.getStreetAddress());
			ps.setString(4, clients.getCity());
			ps.setString(5, clients.getState());
			ps.setString(6, clients.getZipCode());
			ps.setString(7, clients.getEmail());
			ps.setString(8, clients.getPhoneNumber());
			ps.setInt(9, id);

			int i = ps.executeUpdate();

			if (i != 1) {
				throw new SQLException("Unable to update a client with a client id of "+ id);		
			} 

		}
		return new Clients(id, clients.getFirstName(), clients.getLastName(), clients.getStreetAddress(), clients.getCity(), clients.getState(),
				clients.getZipCode(), clients.getEmail(), clients.getPhoneNumber());
	}

	public boolean deleteClientsById(int id) throws SQLException {
		
		boolean success = false;

		try (Connection con = JDBCUtility.getConnection()) {

			String sql = "DELETE FROM clients WHERE client_id = ?;";
			PreparedStatement ps = con.prepareStatement(sql);

			ps.setInt(1, id);

			int i = ps.executeUpdate();

			if (i != 1) {
				throw new SQLException("Delete unsuccessful! CLient does not exist");
			}
			success = true;
		}
		return success;
	}
	
}
